del files\carlogo\q2monp--.tim
del files\carlogo\q2monq--.tim
del files\carlogo\q2morp--.tim
del files\carlogo\q2morq--.tim
del files\carlogo\q2s4np--.tim
del files\carlogo\q2s4nq--.tim
del files\carlogo\q2s4rp--.tim
del files\carlogo\q2s4rq--.tim
del files\carlogo\q2sgrp--.tim
del files\carlogo\q2sgrq--.tim
del files\carlogo\q2stnp--.tim
del files\carlogo\q2stnq--.tim
del files\carlogo\q2strp--.tim
del files\carlogo\q2strq--.tim
del files\carlogo\q2trnp--.tim
del files\carlogo\q2trnq--.tim
del files\carlogo\q2trrp--.tim
del files\carlogo\q2trrq--.tim
del files\carlogo\q2txnp--.tim
del files\carlogo\q2txnq--.tim
del files\carlogo\q2txrp--.tim
del files\carlogo\q2txrq--.tim
del files\carlogo\q2x4np--.tim
del files\carlogo\q2x4nq--.tim
del files\carlogo\q2x4rp--.tim
del files\carlogo\q2x4rq--.tim
