del files\carlogo\ne14np--.tim
del files\carlogo\ne14nq--.tim
del files\carlogo\ne14rp--.tim
del files\carlogo\ne14rq--.tim
del files\carlogo\ne15np--.tim
del files\carlogo\ne15nq--.tim
del files\carlogo\ne15rp--.tim
del files\carlogo\ne15rq--.tim
del files\carlogo\ns14nn--.tim
del files\carlogo\ns14no--.tim
del files\carlogo\ns14np--.tim
del files\carlogo\ns14nq--.tim
del files\carlogo\ns14rn--.tim
del files\carlogo\ns14ro--.tim
del files\carlogo\ns14rp--.tim
del files\carlogo\ns14rq--.tim
del files\carlogo\ns15nn--.tim
del files\carlogo\ns15no--.tim
del files\carlogo\ns15np--.tim
del files\carlogo\ns15nq--.tim
del files\carlogo\ns15rn--.tim
del files\carlogo\ns15ro--.tim
del files\carlogo\ns15rp--.tim
del files\carlogo\ns15rq--.tim
