del files\carlogo\s2fonp--.tim
del files\carlogo\s2fonq--.tim
del files\carlogo\s2forp--.tim
del files\carlogo\s2forq--.tim
del files\carlogo\s2iwnp--.tim
del files\carlogo\s2iwnq--.tim
del files\carlogo\s2iwrp--.tim
del files\carlogo\s2iwrq--.tim
del files\carlogo\s2iwsp--.tim
del files\carlogo\s2iwsq--.tim
del files\carlogo\s2lbnp--.tim
del files\carlogo\s2lbnq--.tim
del files\carlogo\s2lbrp--.tim
del files\carlogo\s2lbrq--.tim
del files\carlogo\s2lgnp--.tim
del files\carlogo\s2lgnq--.tim
del files\carlogo\s2lgrp--.tim
del files\carlogo\s2lgrq--.tim
del files\carlogo\s2lwnp--.tim
del files\carlogo\s2lwnq--.tim
del files\carlogo\s2lwrp--.tim
del files\carlogo\s2lwrq--.tim
del files\carlogo\s2ninp--.tim
del files\carlogo\s2ninq--.tim
del files\carlogo\s2nirp--.tim
del files\carlogo\s2nirq--.tim
del files\carlogo\s2nisp--.tim
del files\carlogo\s2nisq--.tim
del files\carlogo\s2nwnp--.tim
del files\carlogo\s2nwnq--.tim
del files\carlogo\s2nwrp--.tim
del files\carlogo\s2nwrq--.tim
del files\carlogo\s2nwsp--.tim
del files\carlogo\s2nwsq--.tim
del files\carlogo\s2v4np--.tim
del files\carlogo\s2v4nq--.tim
del files\carlogo\s2v4rp--.tim
del files\carlogo\s2v4rq--.tim
del files\carlogo\s2wwnp--.tim
del files\carlogo\s2wwnq--.tim
del files\carlogo\s2wwrp--.tim
del files\carlogo\s2wwrq--.tim
del files\carlogo\s2wwsp--.tim
del files\carlogo\s2wwsq--.tim
del files\carlogo\s236nn--.tim
del files\carlogo\s236no--.tim
del files\carlogo\s236np--.tim
del files\carlogo\s236nq--.tim
del files\carlogo\s236rn--.tim
del files\carlogo\s236ro--.tim
del files\carlogo\s236rp--.tim
del files\carlogo\s236rq--.tim
del files\carlogo\sipanp--.tim
del files\carlogo\sipanq--.tim
del files\carlogo\siparp--.tim
del files\carlogo\siparq--.tim
del files\carlogo\sipcnp--.tim
del files\carlogo\sipcnq--.tim
del files\carlogo\sipcrp--.tim
del files\carlogo\sipcrq--.tim
del files\carlogo\sipwnp--.tim
del files\carlogo\sipwnq--.tim
del files\carlogo\sipwrp--.tim
del files\carlogo\sipwrq--.tim
del files\carlogo\sipznp--.tim
del files\carlogo\sipznq--.tim
del files\carlogo\sipzrp--.tim
del files\carlogo\sipzrq--.tim
del files\carlogo\slganp--.tim
del files\carlogo\slganq--.tim
del files\carlogo\slgarp--.tim
del files\carlogo\slgarq--.tim
del files\carlogo\slgbnp--.tim
del files\carlogo\slgbnq--.tim
del files\carlogo\slgbrp--.tim
del files\carlogo\slgbrq--.tim
del files\carlogo\slgnnp--.tim
del files\carlogo\slgnnq--.tim
del files\carlogo\slgnrp--.tim
del files\carlogo\slgnrq--.tim
del files\carlogo\slgwnp--.tim
del files\carlogo\slgwnq--.tim
del files\carlogo\slgwrp--.tim
del files\carlogo\slgwrq--.tim
del files\carlogo\ssv4nn--.tim
del files\carlogo\ssv4no--.tim
del files\carlogo\ssv4rn--.tim
del files\carlogo\ssv4ro--.tim
del files\carlogo\ssvxnn--.tim
del files\carlogo\ssvxno--.tim
del files\carlogo\ssvxnp--.tim
del files\carlogo\ssvxnq--.tim
del files\carlogo\ssvxrn--.tim
del files\carlogo\ssvxro--.tim
del files\carlogo\ssvxrp--.tim
del files\carlogo\ssvxrq--.tim
