del files\carobj\fp2xr.*
del files\carobj\fp4un.*
del files\carobj\fp4ur.*
del files\carobj\fp27n.*
del files\carobj\fp27r.*
del files\carobj\t2h8r.*
del files\carobj\t2h9r.*
del files\carobj\t22hn.*
del files\carobj\t22hr.*
del files\carobj\us35n.*
del files\carobj\us35r.*
del files\carobj\us50n.*