del files\carlogo\t292nn--.tim
del files\carlogo\t292no--.tim
del files\carlogo\t292rn--.tim
del files\carlogo\t292ro--.tim
del files\carlogo\t2isnn--.tim
del files\carlogo\t2isno--.tim
del files\carlogo\t2isrn--.tim
del files\carlogo\t2isro--.tim
del files\carlogo\t2lgnn--.tim
del files\carlogo\t2lgno--.tim
del files\carlogo\t2lgnp--.tim
del files\carlogo\t2lgnq--.tim
del files\carlogo\t2lgrn--.tim
del files\carlogo\t2lgro--.tim
del files\carlogo\t2lgrp--.tim
del files\carlogo\t2lgrq--.tim
del files\carlogo\t2lsnn--.tim
del files\carlogo\t2lsno--.tim
del files\carlogo\t2lsrn--.tim
del files\carlogo\t2lsro--.tim
del files\carlogo\t2msnp--.tim
del files\carlogo\t2msnq--.tim
del files\carlogo\t2msrp--.tim
del files\carlogo\t2msrq--.tim
del files\carlogo\t2o3nn--.tim
del files\carlogo\t2o3no--.tim
del files\carlogo\t2o3np--.tim
del files\carlogo\t2o3nq--.tim
del files\carlogo\t2o3rn--.tim
del files\carlogo\t2o3ro--.tim
del files\carlogo\t2o3rp--.tim
del files\carlogo\t2o3rq--.tim
del files\carlogo\t2s3nn--.tim
del files\carlogo\t2s3no--.tim
del files\carlogo\t2s3np--.tim
del files\carlogo\t2s3nq--.tim
del files\carlogo\t2s3rn--.tim
del files\carlogo\t2s3ro--.tim
del files\carlogo\t2s3rp--.tim
del files\carlogo\t2s3rq--.tim
del files\carlogo\t2vznp--.tim
del files\carlogo\t2vznq--.tim
del files\carlogo\t2vzrp--.tim
del files\carlogo\t2vzrq--.tim
del files\carlogo\t2xxnn--.tim
del files\carlogo\t2xxno--.tim
del files\carlogo\t2xxnp--.tim
del files\carlogo\t2xxnq--.tim
del files\carlogo\t2xxrn--.tim
del files\carlogo\t2xxro--.tim
del files\carlogo\t2xxrp--.tim
del files\carlogo\t2xxrq--.tim
del files\carlogo\tsgtnn--.tim
del files\carlogo\tsgtno--.tim
del files\carlogo\tsgtnp--.tim
del files\carlogo\tsgtnq--.tim
del files\carlogo\tsgtrn--.tim
del files\carlogo\tsgtro--.tim
del files\carlogo\tsgtrp--.tim
del files\carlogo\tsgtrq--.tim
del files\carlogo\tsonnn--.tim
del files\carlogo\tsonno--.tim
del files\carlogo\tsonnp--.tim
del files\carlogo\tsonnq--.tim
del files\carlogo\tsonrn--.tim
del files\carlogo\tsonro--.tim
del files\carlogo\tsonrp--.tim
del files\carlogo\tsonrq--.tim
del files\carlogo\tsornn--.tim
del files\carlogo\tsorno--.tim
del files\carlogo\tsornp--.tim
del files\carlogo\tsornq--.tim
del files\carlogo\tsorrn--.tim
del files\carlogo\tsorro--.tim
del files\carlogo\tsorrp--.tim
del files\carlogo\tsorrq--.tim
del files\carlogo\tspnnn--.tim
del files\carlogo\tspnno--.tim
del files\carlogo\tspnnp--.tim
del files\carlogo\tspnnq--.tim
del files\carlogo\tspnrn--.tim
del files\carlogo\tspnro--.tim
del files\carlogo\tspnrp--.tim
del files\carlogo\tspnrq--.tim
del files\carlogo\tsprnn--.tim
del files\carlogo\tsprno--.tim
del files\carlogo\tsprnp--.tim
del files\carlogo\tsprnq--.tim
del files\carlogo\tsprrn--.tim
del files\carlogo\tsprro--.tim
del files\carlogo\tsprrp--.tim
del files\carlogo\tsprrq--.tim
